// auto_generated_mod.rs

// generated by `cargo auto` automation task
// Please, don't modify manually the special "region: generated..." that are filled by automation.

use crate::cln_methods_mod::cln_cargo_tree_mod::*;
use crate::cln_methods_mod::cln_config_mod::*;
use crate::cln_methods_mod::cln_publisher_item_mod::*;
use crate::cln_methods_mod::cln_publisher_list_mod::*;
use crate::cln_methods_mod::cln_review_item_mod::*;
use crate::cln_methods_mod::cln_review_list_mod::*;
use crate::cln_methods_mod::cln_utils_mod::*;
use crate::cln_methods_mod::cln_version_mod::*;

/// match the string and call a function
pub async fn match_response_method_and_call_function(response: common_structs_mod::RpcResponse) {
    match response.response_method.as_str() {
        // region: generated match_response_method
        "cln_cargo_tree_list" => cln_cargo_tree_list(response),
        "cln_config_edit" => cln_config_edit(response),
        "cln_modal_close" => cln_modal_close(response),
        "cln_modal_error" => cln_modal_error(response),
        "cln_no_action" => cln_no_action(response),
        "cln_publisher_edit_modal" => cln_publisher_edit_modal(response),
        "cln_publisher_list" => cln_publisher_list(response),
        "cln_publisher_new_modal" => cln_publisher_new_modal(response),
        "cln_review_edit" => cln_review_edit(response),
        "cln_review_list" => cln_review_list(response),
        "cln_review_new" => cln_review_new(response),
        "cln_review_publish_modal" => cln_review_publish_modal(response),
        "cln_version_list" => cln_version_list(response),
        // endregion: generated match_response_method
        _ => log::error!("Error: Unrecognized response_method {}", response.response_method),
    }
}

// proxy for public functions on server
pub mod srv_methods {
    use crate::html_mod::post_request_await_run_response_method;
    use function_name::named;

    // region: generated srv_methods

    #[named]
    pub fn srv_cargo_tree_project<T>(request_data: T)
    where
        T: serde::Serialize,
    {
        let request_method = function_name!();
        post_request_await_run_response_method(request_method, request_data);
    }

    #[named]
    pub fn srv_config_edit<T>(request_data: T)
    where
        T: serde::Serialize,
    {
        let request_method = function_name!();
        post_request_await_run_response_method(request_method, request_data);
    }

    #[named]
    pub fn srv_config_save<T>(request_data: T)
    where
        T: serde::Serialize,
    {
        let request_method = function_name!();
        post_request_await_run_response_method(request_method, request_data);
    }

    #[named]
    pub fn srv_correct_digest<T>(request_data: T)
    where
        T: serde::Serialize,
    {
        let request_method = function_name!();
        post_request_await_run_response_method(request_method, request_data);
    }

    #[named]
    pub fn srv_list_unclean_crates<T>(request_data: T)
    where
        T: serde::Serialize,
    {
        let request_method = function_name!();
        post_request_await_run_response_method(request_method, request_data);
    }

    #[named]
    pub fn srv_publisher_delete<T>(request_data: T)
    where
        T: serde::Serialize,
    {
        let request_method = function_name!();
        post_request_await_run_response_method(request_method, request_data);
    }

    #[named]
    pub fn srv_publisher_edit<T>(request_data: T)
    where
        T: serde::Serialize,
    {
        let request_method = function_name!();
        post_request_await_run_response_method(request_method, request_data);
    }

    #[named]
    pub fn srv_publisher_list<T>(request_data: T)
    where
        T: serde::Serialize,
    {
        let request_method = function_name!();
        post_request_await_run_response_method(request_method, request_data);
    }

    #[named]
    pub fn srv_publisher_new<T>(request_data: T)
    where
        T: serde::Serialize,
    {
        let request_method = function_name!();
        post_request_await_run_response_method(request_method, request_data);
    }

    #[named]
    pub fn srv_publisher_save<T>(request_data: T)
    where
        T: serde::Serialize,
    {
        let request_method = function_name!();
        post_request_await_run_response_method(request_method, request_data);
    }

    #[named]
    pub fn srv_review_delete<T>(request_data: T)
    where
        T: serde::Serialize,
    {
        let request_method = function_name!();
        post_request_await_run_response_method(request_method, request_data);
    }

    #[named]
    pub fn srv_review_edit<T>(request_data: T)
    where
        T: serde::Serialize,
    {
        let request_method = function_name!();
        post_request_await_run_response_method(request_method, request_data);
    }

    #[named]
    pub fn srv_review_edit_or_new<T>(request_data: T)
    where
        T: serde::Serialize,
    {
        let request_method = function_name!();
        post_request_await_run_response_method(request_method, request_data);
    }

    #[named]
    pub fn srv_review_new<T>(request_data: T)
    where
        T: serde::Serialize,
    {
        let request_method = function_name!();
        post_request_await_run_response_method(request_method, request_data);
    }

    #[named]
    pub fn srv_review_new_version<T>(request_data: T)
    where
        T: serde::Serialize,
    {
        let request_method = function_name!();
        post_request_await_run_response_method(request_method, request_data);
    }

    #[named]
    pub fn srv_review_open_source_code<T>(request_data: T)
    where
        T: serde::Serialize,
    {
        let request_method = function_name!();
        post_request_await_run_response_method(request_method, request_data);
    }

    #[named]
    pub fn srv_review_publish<T>(request_data: T)
    where
        T: serde::Serialize,
    {
        let request_method = function_name!();
        post_request_await_run_response_method(request_method, request_data);
    }

    #[named]
    pub fn srv_review_save<T>(request_data: T)
    where
        T: serde::Serialize,
    {
        let request_method = function_name!();
        post_request_await_run_response_method(request_method, request_data);
    }

    #[named]
    pub fn srv_reviews_list<T>(request_data: T)
    where
        T: serde::Serialize,
    {
        let request_method = function_name!();
        post_request_await_run_response_method(request_method, request_data);
    }

    #[named]
    pub fn srv_update_registry_index<T>(request_data: T)
    where
        T: serde::Serialize,
    {
        let request_method = function_name!();
        post_request_await_run_response_method(request_method, request_data);
    }

    #[named]
    pub fn srv_version_list<T>(request_data: T)
    where
        T: serde::Serialize,
    {
        let request_method = function_name!();
        post_request_await_run_response_method(request_method, request_data);
    }
    // endregion: generated srv_methods
}

pub mod common_structs_mod {
    // region: generated common_structs_mod
    // common_structs_mod.rs

    //! common structs between the backend and frontend
    //! One automation task will copy it over to cargo_crev_reviews_wasm/auto_generated_mod.rs !

    use serde::{Deserialize, Serialize};

    // region: platform wide structs

    /// the request_method will be processed on the server
    #[derive(Serialize, Deserialize, Debug)]
    pub struct RpcRequest {
        pub request_method: String,
        pub request_data: serde_json::Value,
    }

    /// the response_method will be processed on the client
    #[derive(Serialize, Deserialize, Debug)]
    pub struct RpcResponse {
        pub response_method: String,
        pub response_data: serde_json::Value,
        pub response_html: String,
    }

    /// generic message for Rpc
    #[derive(Serialize, Deserialize, Debug)]
    pub struct RpcMessageData {
        pub message: String,
    }

    /// generic empty data for Rpc
    #[derive(Serialize, Deserialize, Debug)]
    pub struct RpcEmptyData {}
    // endregion: platform wide structs

    // region: review

    #[derive(Serialize, Deserialize, Debug, Default)]
    pub struct ReviewFilterData {
        pub crate_name: String,
        pub crate_version: Option<String>,
        pub old_crate_version: Option<String>,
    }

    #[derive(Serialize, Deserialize, Debug, Default, Clone)]
    pub struct ReviewItemData {
        pub crate_name: String,
        pub crate_version: String,
        pub date: String,
        pub thoroughness: String,
        pub understanding: String,
        pub rating: String,
        pub comment_md: String,
    }

    #[derive(Serialize, Deserialize, Debug, Default)]
    pub struct ReviewListData {
        pub filter: String,
        pub list_of_review: Vec<ReviewItemData>,
    }

    // endregion: review

    #[derive(Serialize, Deserialize, Debug, Default)]
    pub struct CargoTreeItemData {
        pub cargo_tree_line: String,
        pub crate_name_version: Option<String>,
        pub my_rating: Option<String>,
        pub crate_description: Option<String>,
        pub published_by_url: Option<String>,
        pub trusted_publisher: Option<String>,
        pub status: Option<String>,
        pub audit_id: Option<String>,
    }

    #[derive(Serialize, Deserialize, Debug, Default)]
    pub struct CargoTreeListData {
        pub project_dir: String,
        pub list_of_cargo_tree: Vec<CargoTreeItemData>,
    }

    #[derive(Serialize, Deserialize, Debug, Default)]
    pub struct VerifyItemData {
        /// status: none, pass, warn, yanked
        pub status: String,
        /// rating if exists, version number if exists for crate
        pub my_review: String,
        pub crate_name: String,
        pub crate_version: String,
        pub published_by_url: String,
        pub trusted_publisher: String,
    }

    #[derive(Serialize, Deserialize, Debug, Default)]
    pub struct VerifyListData {
        pub project_dir: String,
        pub list_of_verify: Vec<VerifyItemData>,
    }

    #[derive(Serialize, Deserialize, Debug, Default)]
    pub struct VersionItemData {
        pub crate_name: String,
        pub crate_version: String,
        pub yanked: bool,
        pub published_by_url: Option<String>,
        pub published_date: String,
        pub is_src_cached: Option<bool>,
        pub my_review: Option<ReviewItemData>,
    }

    #[derive(Serialize, Deserialize, Debug, Default)]
    pub struct VersionListData {
        pub list_of_version: Vec<VersionItemData>,
    }

    #[derive(Serialize, Deserialize, Debug, Default, Clone)]
    pub struct PublisherItemData {
        pub publisher_url: String,
        pub note: String,
    }

    #[derive(Serialize, Deserialize, Debug, Default)]
    pub struct PublisherListData {
        pub list_of_publisher: Vec<PublisherItemData>,
    }

    #[derive(Serialize, Deserialize, Debug, Default)]
    pub struct PublisherFilterData {
        pub publisher_url: String,
    }

    #[derive(Serialize, Deserialize, Debug, Default, Clone)]
    pub struct ConfigData {
        pub code_editor_path: String,
        pub browser_path: String,
    }
    // endregion: generated common_structs_mod
}
